version: '3.8'

services:
  housenumbers-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-your_super_secret_jwt_key_here_change_in_production}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
      - AUTH_USERNAME=${AUTH_USERNAME:-admin}
      - AUTH_PASSWORD=${AUTH_PASSWORD:-secure_password_123}
      - DATABASE_PATH=./data/database.sqlite
      - MODEL_PATH=./models/phi-2.Q4_0.gguf
      - MODEL_CONTEXT_SIZE=${MODEL_CONTEXT_SIZE:-2048}
      - MODEL_GPU_LAYERS=${MODEL_GPU_LAYERS:-0}
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

volumes:
  data:
  models: