[phases.setup]
nixPkgs = ['nodejs_20', 'python3', 'cmake', 'gcc', 'gnumake']

[phases.build]
cmds = ['npm ci', 'npm run build']

[phases.start]
cmd = 'node dist/index.js'

[variables]
NODE_ENV = 'production'